site_name: "Paketti - A Framework or Firmware update to Renoise"
docs_dir: "Documentation"  # Points to the Documentation folder
theme:
  name: "material"
  palette:
    primary: "indigo"
    accent: "indigo"
    toggle:
      icon: "material/brightness-4"
      name: "Switch to dark mode"
    scheme: "slate"  # Optional: Set default to dark mode
extra_css:
  - Documentation/dark-mode.css   # This includes dark-mode.css in the generated CSS
extra_javascript:
  - dark-light-toggle.js  # Optional: Link JavaScript if you want a dark/light mode toggle
nav:
  - Home: index.md  # This should match the actual home file name, or create one if missing
  - Tools Menu: 01-ToolsMenu.md
  - Instrument Box: 02-InstrumentBox.md
  - Sample Editor: 03-SampleEditor.md
  - Pattern Editor: 04-PatternEditor.md
  - Automation: 05-Automation.md
  - Key Bindings: 22-KeyBindings.md
